name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: npm install
      run: npm install
    - name: Build contracts
      run: npx locklift build
#    - name: Verify contracts for everscan.io
#      run: npx locklift verify
    - name: Run Ansible playbook at ./ansible/playbooks/deploy_dev.yml
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy_dev.yml
        directory: ./ansible/playbooks
        options: |
          -i ../inventory/dev.yml
    - name: Start local ever node
      run: npx everdev se set --port 4321 && npx everdev se start
    - name: Test locklift
      run: npx locklift test --network local